### ISSUE TITLE
Callback should be the last argument

### ISSUE THREAD

**Issue by diversario** [alevy/memjs#53]
Having something other than a callback as the last function argument goes against node conventions and it's inconsistent with other methods in the module that have callback as the last argument.

**Comment by alevy** [comment]
I agree, but for now, it's done for backwards compatability, since some parameters were added after the fact. See #50 for a short discussion on the matter. I plan on making this change eventually, and am more than happy to merge pull requests so long as they either maintain backwards compatability or have a reasonable upgrade path (even if either is hacky for now).

**Comment by rdegges** [comment]
I think the long-term solution to this is to release a major release (1.0.0 type stuff), which breaks backwards compatibility. Semantic Versioning typically works this way: major releases which increase the first number are expected to introduce backwards-compatibility breaking behaviors.

**Comment by dterei** [comment]
Amit, I think there are three options here:

1. Add variants of functions, basic:

        var set = function(key, value, callback)
        var set_ = function(key, value, flags, expires, version)

2. Use a dictionary for all arguments:

        var set = function(args, callback)
        set({key: 'hello', value: 'world'}, function(...

3. Use a dictionary for extended arguments:

        var set = function(key, value, options, callback)
