### ISSUE TITLE
A way to delete key

### ISSUE THREAD

**Issue by iceNuts** [alevy/memjs#69]
Hi there,

I am wondering if there is a way to expire keys using memjs?

Thanks.

**Comment by iceNuts** [comment]
I think the *delete* function only delete the content of a key however doesn't expire the key itself.

**Comment by alevy** [comment]
@iceNuts what do you mean by "expire"? If you mean "set an expiration such that the value is deleted later", that's possible by setting the fourth parameter in `SET` (and `ADD` etc) to a nonzero interval or epoch. Otherwise "expire" doesn't mean anything special in memcache, and I think delete _does_ do what you want.

**Comment by iceNuts** [comment]
@alevy Thanks, what I mean is if there is a way to purge the key as *delete* actually is clear the content associated with the key however, the key is still in memcache.

**Comment by alevy** [comment]
@IceNuts Hrm... It's not. If you do a `delete` on a key, you should notice that both the `bytes` and `curr_items` in stats decreases. `total_items` doesn't decrease because that's a running count of all items that ever existed. How is that that you're seeing that "the key is still in memcache?"
